### ISSUE TITLE
MSBuild Task should accept path to PDB directly

### ISSUE THREAD

**Issue by AArnott** [GitTools/GitLink#104]
The MSBuild Task should accept the path to PDBs directly rather than solution and project files. 
At the moment, it doesn't take Configuration as a property so it will break in Debug builds. 

I volunteer to fix it up, if a committer will likely accept the PR.

**Comment by GeertvanHorrik** [comment]
Yes, we are definitely open for a PR with a fix!

**Comment by AArnott** [comment]
Great. I'll work on that over the next week or two.

**Comment by AArnott** [comment]
I'm looking over the code. I'm seeing a lot of things I either need to change or would like to in order to get this work done. There is a high coupling to MSBuild's evaluation model deeply in the code, rather than just on the outer APIs, which doesn't serve well for an MSBuild task -- or a console app which (IMO) should allow me to specify a .pdb and source files directly without any MSBuild correlation. 
How would you feel about either a large PR or several smaller PRs that refactor the code into a more form that is more adaptable to different use cases?

**Comment by GeertvanHorrik** [comment]
Happy with everything, as long as you keep our coding standards we are basically open to anything (small or large), as long as you don't break use-cases for existing users.

**Comment by AArnott** [comment]
That all sounds fair. :)

**Comment by AArnott** [comment]
I'm having a difficult time fitting into your existing use cases. Let me explain:

The command line tool seems excessively oriented around MSBuild. It claims to take a "solution directory" yet it fails if I don't give it the root directory of the git repo, and somehow it magically finds the solution directory under src. It still can't find my pdb's unless I point it at my output directory manually. 
The command line tool takes a branch name for some reason I can't figure out, since this should always be based on a SHA1 of the commit, which is independent of branch names. 

I think the command line should have this syntax:
`gitlink.exe <pdbfile>`
Done and done. The PDB file points at the source files already, so no need to pass those in. The source files must be in the git repo so you can get the commit and remote from there. MSBuild has nothing whatever to do with any of this.
Now, some cloud build services may not actually preserve the git repo itself but pass in info by environment variable, so you can take *optional* parameters to specify git remote URL and commit ID. 

This would allow a trivial invocation from the command line, and a trivial invocation from an MSBuild target of just:

```xml
<GitLink PdbFile="$(PdbFile)" />
```

And the target that invokes this task should be defined in a NuGetPkgName.targets file in your nuget package so that it automatically is imported by the project you install the package into, and the GitLink.exe should be in the package's tools folder rather than under lib. This would let anyone leverage gitlink as easily as installing the nuget package into their project and they're completely done. I can't find out how to even build the existing gitlinktask package. I can't find a script for it. And there are _two_ gitlink.targets files, for some reason.

There are a ton of very small methods in this project that work with abstractions that could have made this more general, but instead they tightly couple msbuild to everything, which ironically makes it very difficult to implement an MSBuild task (which doesn't have an msbuild Project object). 

I'm willing to fix all of this, but after trying for a couple hours to 'fit in' to the existing code and use cases, I'm giving up. I'm going to rip it apart and reassemble it with the layering that would make it very reusable in lots of different use cases (including MSBuild as this project has it today, if someone wanted to do it that way), and personally focus on the MSBuild task, and perhaps the simpler command line scenario I propose above. I'll at least consume this fork myself. If you're still willing to take a pull request (and bump the major version for the breaking changes it would entail), I would be happy to send it and keep contributing here as needed. Otherwise I suppose I'll maintain a fork for my own consumption.

I hope this doesn't come across as offensive at all. I'm very impressed with what the project accomplishes and it seems to do the best job of a few options I've seen. Please consider what I've written as an offer to (as I see it anyway) dramatically improve it, but at the cost of your existing users hitting a road bump of having to simplify their invocation of this tool when they upgrade.

What do you think?

**Comment by GeertvanHorrik** [comment]
Happy to bump to 3.0 and introduce breaking changes. The product was originally created so we could easily update the pdbs so we could step through the source code of our own tooling and slowly became used by others. 

What if we introduce a mode argument? We could have something like this:

```
GitLink MyPdbFile.pdb -mode pdb
```

Your msbuild task would look like this:

```
<GitLink PdbFile="$(PdbFile)" Mode="pdb" />
```

The reason the tool checks for an sln directory is because it allows us to automatically take care of things (for example, check the projects, find the output directory (even when outside the sln directory). This way we can easily apply this tool on a build server without having to specify too many parameters.

> and the GitLink.exe should be in the package's tools folder rather than under lib

We have another issue for this, we are considering it. The reason we put it into the lib folder is so that people could write automation tools if they wanted to. If people really want to use the tool, they could install it using chocolatey (that was our thought at the time). 

> I can't find out how to even build the existing gitlinktask package. I can't find a script for it

We are currently using FinalBuilder as a build script (which we use for a lot of open source projects to easily deploy stuff). We can convert this to cakebuild so it's easier to run for the people that don't have a FinalBuilder license.

I think we should do 1 thing at a time though. What if we start with the build script, that's the easiest to convert. Happy to help with that as well. Once that is converted, we can deploy quickly and test the changes that will have more impact on a future release (e.g. 3.0).

**Comment by AArnott** [comment]
Nice. 

> What if we introduce a mode argument? 

I'm not sure what the mode argument is for. If we want to support taking pdbs as well as sln files on the command line I think we can make that work a bit more automatically than having to specify the mode explicitly. Let's see how it goes. But we wouldn't need it for the MSBuild task. The MSBuild task should never take a solution or project file, as tasks aren't supposed to ever load msbuild projects, but rather take all their parameters directly from the executing project.

> We can convert this to cakebuild so it's easier to run for the people that don't have a FinalBuilder license.

I actually was thinking something more 'built-in' for everyone. I can build nuget packages with msbuild using NuProj, without requiring any additional software to be installed than what ever VS user already has. I'm a huge fan of "git clone && nuget restore && msbuild = done". In some cases I have to replace 'nuget restore' with 'init.ps1' when it gets more interesting, like for NPM restore and others.

> I think we should do 1 thing at a time though.

I'm happy to try. Last night I migrated packages.config to project.json, and got tests to run in VS without having to install any NUnit extension. I'm happy to share incremental PRs. But I'm not sure how well at least our intermediate goals will align. For example, I ripped out the assembly merging and .exe embedding you had going on. I wanted something simpler and more familiar to work with, and I didn't see the value of having just one file when all the acquisition modes bring the file down in its own directory anyway. After my refactoring is done, if you really want to bring that back, I can live with it, probably. But for now, I like to work with a more familiar, standard toolset.

**Comment by AArnott** [comment]
Oh, I also fixed NUnit test runs to not fail while debugging, and to use NUnit 3 instead of 2.

**Comment by GeertvanHorrik** [comment]
The reason we embed the executable (with costura) is so we have a single executable without any dependencies for people to install. 

Updating to NUnit 3 was still on the roadmap (but we have a build server with about 100 projects so wanted to do that all in a batch, but good you already did this one).

**Comment by AArnott** [comment]
> so we have a single executable without any dependencies for people to install.

But what value is there, when users acquire it by package managers? Who cares how many files make it up?

**Comment by AArnott** [comment]
Any idea why the GettingProjectsFromSolution_* tests pass in isolation and fail when run as a batch with the rest?

**Comment by GeertvanHorrik** [comment]
Not everyone acquires it via package managers, some prefer to copy the file over manually. Why wouldn't we want to deploy it as a single file ;-)

**Comment by GeertvanHorrik** [comment]
Seems to run fine on the build server (but this is NUnit 2, checking out with 3 on my machine now).

![image](https://cloud.githubusercontent.com/assets/1246444/19213580/a556d13e-8d6f-11e6-93e6-16347bc311ae.png)

**Comment by AArnott** [comment]
Try the develop branch in my fork where I've already migrated, if you want.

**Comment by AArnott** [comment]
> Why wouldn't we want to deploy it as a single file ;-)

Well, a few things occur to me:

1. It's confusing when you're debugging or referencing it to understand where all the extra types are coming from
1. It's unusual. Not typical .NET dependencies.
1. Copyright/redist concerns, potentially. For example, srcsrv.exe is licensed to redist, but you redist it without any notices attached for the user to review. I'm not sure this is kosher. It might be, but it's always a concern.
1. When folks want to develop consumers of this assembly but packaged in a different way, and if they happen to want to reference the same assemblies you have, now the assemblies have to get shipped twice, and the CLR may not recognize type equivalence.

**Comment by AArnott** [comment]
Should we move the discussion to gitter?

**Comment by AArnott** [comment]
The tests fail because `ProjectHelper.SolutionParserType` is null, but the static ctor at least _seems_ to guarantee that shouldn't be the case. Drilling in...

**Comment by AArnott** [comment]
Ah, `TypeCache.GetType` returns null. I wonder if it's a thread-safety issue. I'm not familiar with this class.

**Comment by AArnott** [comment]
Oh, regarding your convenient invocation of gitlink from build servers comment, my approach to this is the msbuild target in nuget package. Projects just install that, then you get the behavior on all build servers and local builds automatically.

**Comment by GeertvanHorrik** [comment]
Please move to gitter, then we can put final thoughts here
