### ISSUE TITLE
Source codes from UNC

### ISSUE THREAD

**Issue by maraf** [GitTools/GitLink#131]
Is there any support for UNC paths? I would like to host my sources on a network shared folder. but passing directly UNC path to the `-u` parameter results in a message saying that provider is not recognized.

**Comment by GeertvanHorrik** [comment]
I think this should be possible because basically srcsrv files just remap source files to a new location. But we don't support it out of the box yet. Interested in doing a PR?

**Comment by maraf** [comment]
Yes, I am!
