### ISSUE TITLE
Need to rename the pdf.srcsrv file?

### ISSUE THREAD

**Issue by v-jacai** [GitTools/GitLink#134]
Here is the my steps:
1. Build my solution, it will generate the .dll and .pdb file. 
2. Run the GitLink command, it will generate one .pdb.srcsrv file. 

Before I create the Nuget package, do I need to delete the original .pdb file and rename the .pdb.srcsrv to .pdb file?

**Comment by GeertvanHorrik** [comment]
GitLink will update the pdb. You don't need to delete the original pdb. You only need to embed the updated pdb files with your assemblies.

**Comment by v-jacai** [comment]
Thanks for your response, How can I embed the original .pdb files with assemblies?

Also, can you explain some why did you generated the .pdb.csv file? what's purpose?

**Comment by GeertvanHorrik** [comment]
The src file is an intermediate file. You can embed the pdb by just copying it next to the assembly when generating your nuget packages.

**Comment by v-jacai** [comment]
Thanks! If I have to debug it in Visual Studio in administrator permission?

**Comment by GeertvanHorrik** [comment]
Depends on your vs version. I think VS 2013 and later don't require this.

**Comment by v-jacai** [comment]
thanks! awesome!
