### ISSUE TITLE
Generated NuGet with NuProj generates too much content

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitLink#138]
This is what currently is included inside a generated NuPkg:

![image](https://cloud.githubusercontent.com/assets/1246444/22065725/ca3c5950-dd89-11e6-9f1c-9781544f56a7.png)

Do we want a separate NuGet package for the Task project?

/cc @AArnott

**Comment by GeertvanHorrik** [comment]
And we also should check if this is compatible with Chocolatey.

**Comment by AArnott** [comment]
Yes, it works with chocolatey. Pdbgit is already there and approved. 
Why do you say there are too many files in the package? They are all necessary for either msbuild or cmdline. Splitting them up makes everyone have to be more aware of the difference, so unless folks are complaining about the package size and removing a small fraction of it would fix it, I don't see any changes necessary here.

**Comment by GeertvanHorrik** [comment]
My assumption was that we would be creating separate packages:

- GitLink
- GitLinkTask

So if someone wants to reference just gitlink / install it as a tool, they can use GitLink. If they want the task, they can reference GitLinkTask.

**Comment by AArnott** [comment]
IMO we should wait for a few customers to demand that. They can already get it as a tool via Chocolatey. And if they really want to use nuget to get the tool, they can use their solution-level packages.config to install it and thereby bypass the msbuild files that would be inserted into their project.

I suspect most folks (at least, folks who have used PdbGit already and other packages that people tend to use to customize their build) appreciate that they just install and it works. And if "GitLink" doesn't "just work" they'll probably either ditch it or contrive some complicated hookup before some of them realize that they installed the wrong nuget package.

**Comment by GeertvanHorrik** [comment]
Closing ticket, we can re-open if we want to re-evaluate.
