### ISSUE TITLE
Alpha 3.0.0 is built with package version 1.0.0

### ISSUE THREAD

**Issue by kzu** [GitTools/GitLink#144]
https://ci.appveyor.com/project/GitTools/gitlink/build/3.0.0-alpha.82.build.64

Would love to try the new 3.0.0 ASAP, so if that could be somehow released as an alpha... :)

Thanks!

**Comment by GeertvanHorrik** [comment]
Today we released the first alpha of 3.0.0 to both chocolatey and nuget.
