### ISSUE TITLE
FAQ - Improve the documentation

### ISSUE THREAD

**Issue by Korporal** [GitTools/GitLink#148]
I'm encountering GitLink for the first time and have read the associated readme file but still have questions.

It seems there are two distinct audiences for GitLink documentation:

* Consumers of code hosted under Git.
* Creators of consumable code hosted under Git.

So if I want to be able to debug with source support, code hosted on GitHub, that's a specific use case, whereas if I want to create/publish code so that other can debug it with source that's the other use case.

It would help if the readme was structured better to delineate these two use cases.

Here are some questions:

1. Do I need to install the GitLink nuget package when I'm a publisher or consumer? 
2. Does use of GitLink require we publish our code as a NuGet package in order for others to use GitLink to debug it?
3. Can we use GitLink in a simpler way if we only want to debug our own GitHub hosted code?
4. I installed the GitLink NuGet package into a simple test console app but the only changes I saw were to the project file (added a reference) and the packages.config - I saw no other changes and don't see how my building my test app can include any additional GitLink steps?

Thx

**Comment by GeertvanHorrik** [comment]
1. Only as publisher, the consumer only has to enable source server in VS
2. You need to distribute your assemblies (dll or exe) together with an *updated* (GitLinked) pdb file. We think NuGet is the easiest, but you could even manually deploy everything on a network share.
3. I'm not sure how this process could be any easier. If you have a build server with continuous integration, it should publish everything correctly each time. Of course if you have ideas to make this process easier, we'd love to hear about it. For example, GL 3.0 (currently in alpha) has msbuild integration which always makes sure your output is GitLinked.
4. Correct, you don't need other references. GitLink should only be run once and the only thing it does is update your pdb file by adding redirects from local files => hosted files.

**Comment by Korporal** [comment]
Thanks

re: 3. By easier I mean can we avoid/disregard the fact that our repo(s) are private if we're primarily interested in debugging only our own Github hosted code? That is if a shop are using their own private nuget server to host their own nuget packages who's source is in their own private repo - can GitLink be setup/configured to avoid these authenticatin things you mention with private repos?

**Comment by GeertvanHorrik** [comment]
No, because in the end it's VS that is doing the remapping to the remotes (private repo in this case). I believe we have support for authentication via powershell, but not 100 % sure since it was created as a PR.

**Comment by GeertvanHorrik** [comment]
Closing this ticket since we believe the questions have been answered. If not, feel free to re-open.
