### ISSUE TITLE
Visual Studio (401) Unauthorized when download

### ISSUE THREAD

**Issue by v-jacai** [GitTools/GitLink#150]
I used the cusotmer URL in GitLink and I am able to link the srcsrv information to pdb file. 
However when I debug into the file in Visual Studio 2013, it say below error in output window. 
SRCSRV:  powershell -NoProfile -Command "(New-Object System.Net.WebClient).DownloadFile('cutomerURL', 'MyLocalPath')"
         Exception calling "DownloadFile" with "2" argument(s): "The remote server 
         returned an error: (401) Unauthorized."At line:1 char:1
         + (New-Object System.Net.WebClient).DownloadFile('http://tfs.wlb2.eur.n ...
         + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
             + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
             + FullyQualifiedErrorId : WebException

Any advise on this to resolve the issue? 
BTW, after I added UseDefaultCredentials = true; it works fine, but I don't like to build one personal gitlink in my local. thanks!

**Comment by GeertvanHorrik** [comment]
Unfortunately authentication is not yet supported.

**Comment by v-jacai** [comment]
I add it on SrcSrv file: 
 if(downloadWithPowershell)
                    {
                        sw.WriteLine("TRGFILE=%fnbksl%(%targ%%var2%)");
                        sw.WriteLine("SRCSRVTRG=%TRGFILE%");                        
                        sw.WriteLine("SRCSRVCMD=powershell invoke-command -scriptblock {$webClient = New-Object System.Net.WebClient; $webClient.UseDefaultCredentials = $true; $webClient.DownloadFile('%RAWURL%', '%TRGFILE%');}");
                    }
I will create one pull request for this.

**Comment by v-jacai** [comment]
Thanks, what's the next release date? Can I see my changes in the release? I need the latest version in my project.

**Comment by GeertvanHorrik** [comment]
We don't have a fixed date yet, but we do release alphas so if you want I can release one right now.

**Comment by v-jacai** [comment]
I am appreciate it if I can get the latest version right now.

**Comment by GeertvanHorrik** [comment]
3.0.0-alpha.90.build.71 should be available on both nuget & chocolatey now.

**Comment by v-jacai** [comment]
Awesome! Looking forward to have one stable version soon.
