### ISSUE TITLE
Visual Studio 2017 & new .csproj support

### ISSUE THREAD

**Issue by hikalkan** [GitTools/GitLink#154]
Does Gitlink support Visual Studio 2017 & new .csproj format?
My project also targets to multiple frameworks (https://github.com/aspnetboilerplate/aspnetboilerplate/blob/dev/src/Abp/Abp.csproj#L6)

First, I tried to add Gitlink 2.4.1 to my project. I got a warning indicates that this does not support .netstandard. Anyway, it didn't work. I tried latest unstable package which didn't work also.

I tried to run Gitlink.exe (3.0.0-unstable0090) manually to run this command:

````
GitLink.exe src\Abp\bin\Release\net46\Abp.pdb
````

and I got an error:

![image](https://cloud.githubusercontent.com/assets/1210527/26153311/6dccf822-3b13-11e7-80ac-95fcc149d41c.png)

**Comment by ctaggart** [comment]
That is probably a portable pdb file. GitLink & SourceLink v1 support Windows PDB files. Can you try SourceLink v2? You can read more about it here. https://github.com/ctaggart/SourceLink/. We are [working together](https://github.com/ctaggart/SourceLink/issues/178) on it.

**Comment by hikalkan** [comment]
It seems SourceLink properly working. Thanks a lot.
