### ISSUE TITLE
Generated file incorrectly causing GitLink to fail

### ISSUE THREAD

**Issue by jaredpar** [GitTools/GitLink#155]
Consider the following code in [https://github.com/GitTools/GitLink/blob/develop/src/GitLink/Linker.cs#L59](Linker.cs).  

``` c#
string someSourceFile = sourceFiles.FirstOrDefault();
...

repositoryDirectory = GitDirFinder.TreeWalkForGitDir(Path.GetDirectoryName(someSourceFile));
if (repositoryDirectory == null)
{
    Log.Error("No source files found that are tracked in a git repo.");
    return false;
}
```

This is choosing an arbitrary single file from the PDB.  If that file can't be located in Git then it causes the entire linking process to fail on the apparent assumption that no files are tracked in Git.  There are a couple of problems with this:

1. The error message doesn't line up with the behavior.  It's not that **no** files exist in the Git repo, it's that a **single arbitrary** file does not exist. 
2. Consider the case where the Obj directory is located outside the cone of .git (a not so uncommon practice).  If the `someSourceFile` happens to be a generated file, say AssemblyAttributes.cs, then GitLink will fail to run.  

The second issue is a blocker right now for Roslyn.  We have a number of files generated into Obj and it is causing GitLink to refuse to run on about 1/2 of our PDBs.  Pretty much breaks our GitLink story.

**Comment by GeertvanHorrik** [comment]
Thanks for reporting. I noticed you already created a PR for the exit code. We'll look into the other issue once 2 has been merged.

**Comment by jaredpar** [comment]
Ended up finding a way around this.  If we explicitly pass `--baseDir` we can avoid this block of code and unblock ourselves.

**Comment by jairbubbles** [comment]
Bumped exactly into the same issue (the first file was a tmp one). Thx for the fix!
