### ISSUE TITLE
Build environment doesn't respect %NUGET_PACKAGES% 

### ISSUE THREAD

**Issue by jaredpar** [GitTools/GitLink#162]
The environment variable `%NUGET_PACKAGES%` is used to override the location where NuGet packages are restored to. The GitLink repo respects this during restore. But in build files when looking for artifacts it assumes they are always restored to `%USERPROFILE%\.nuget`.  

Example from [GitLink.NuGet.nuproj](https://github.com/GitTools/GitLink/blob/develop/src/GitLink.NuGet/GitLink.NuGet.nuproj#L17)

``` xml
    <NuProjPath>$(UserProfile)\.nuget\packages\NuProj\0.11.14-beta\tools</NuProjPath>
```

**Comment by jaredpar** [comment]
Working on a fix for this.

**Comment by GeertvanHorrik** [comment]
Cool, thanks. Then we'll wait with the v3 release which we wanted to release soon.
