### ISSUE TITLE
Add support for native PDBs

### ISSUE THREAD

**Issue by jairbubbles** [GitTools/GitLink#166]
Native PDBs are currenlty failing but it's not missing much. The PDB is correctly parsed but it's failing at getting source files. Other than that the call to pdbstr.exe is working perfectly.

The problem is that PDB file format is quite complicated, I quickly looked at Microst.cci using this [PdbReader](https://github.com/Microsoft/cci/blob/master/PDBReaderAndWriter/PdbReader/SourceLocationProvider.cs) but we end with the same results (GetSourceFiles() return no files).
There are other examples using Dia SDK but I guess we can't use that as it's quite complicated (and not portable).

**Comment by GeertvanHorrik** [comment]
Did you try the unstable (msbuild) version or the latest stable one?

**Comment by jairbubbles** [comment]
I cloned the depot (develop branch).

FYI I'm currently trying to add an option IndexAllDepotFiles as native PDB doesn't seem to include the list of all source files. I guess it's not a big deal to index too many files.

**Comment by GeertvanHorrik** [comment]
Currently releasing 3.0 stable, this is a great one for 3.1.

**Comment by jairbubbles** [comment]
Cool I'll create a WIP merge request ASAP so you can look at it.
