### ISSUE TITLE
Ignore generatedinternaltypehelper.g.cs instead of generating a warning

### ISSUE THREAD

**Issue by batzen** [GitTools/GitLink#190]
### Steps to reproduce

1. Clone https://github.com/fluentribbon/Fluent.Ribbon.git
2. Run the powershell script build.ps1

Platform:
.NET version: 4.0, 4.5, 4.6.2

### Expected behaviour

GitLink should not generate warnings for generatedinternaltypehelper.g.cs.

### Actual behaviour

GitLink generates the following warning
```
C:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\packages\gitlink\build\GitLink.targets(9,5): warning : Unable to find file in git: "c:\dev\oss_own\fluentribbon\fluent.ribbon\obj\fluent\releasev4.6.2\generatedinternaltypehelper.g.cs". [C:\DEV\OSS_Own\FluentRibbon\Fluent.Ribbon\Fluent.Ribbon\Fluent.Ribbon.NET 4.6.2.csproj]
```

**Comment by batzen** [comment]
Thinking about it a bit more, shouldn't all ".g.cs" files be ignored?

**Comment by GeertvanHorrik** [comment]
Good point, thanks for letting us know.

**Comment by GeertvanHorrik** [comment]
Releasing a new nightly now.

**Comment by GeertvanHorrik** [comment]
Could you please let us know whether 3.2.0-alpha.25.build.128 solves your issue?

**Comment by batzen** [comment]
Thanks a lot. Will give it a try tomorrow.

**Comment by batzen** [comment]
Just updated to the latest unstable version from nuget.
The warning about .g.cs went away, but now i get:

`error MSB4064: The "IntermediateOutputPath" parameter is not supported by the "LinkPdbToGitRemote" task. Verify the parameter exists on the task, and it is a settable public instance property.`

**Comment by batzen** [comment]
Maybe that warning is my own fault. Will have a look at that later.

**Comment by batzen** [comment]
Ok, warning was my own fault.
I consider this issue fixed.

**Comment by GeertvanHorrik** [comment]
Thanks for the feedback.

**Comment by moescs** [comment]
The latest unstable version in nuget (3.2.0-unstable0040) still generates lots of warnings about .g.cs files for me. However, I'm using the command line. The -s or --skipVerify option seems to have no effect.
