### ISSUE TITLE
Add Gitlab support

### ISSUE THREAD

**Issue by Liryna** [GitTools/GitLink#192]
### Feature description

Hi,

I am looking to make the gitlab integration.
We can access to raw files the same way as github but with a basic api token.
`https://gitlab.com/repo/raw/${git_commit}/...?private_token=YOUR_TOKEN`
See: https://gitlab.com/gitlab-org/gitlab-ce/issues/19077

I wonder if we should 'just' add a param after `-u` to provide extram param on the URL ? or a param to say we are using gitlab ?
Can someone guide me how this could be integrated in Gitlink ?

(I would contribute it to the project ofc)

**Comment by GeertvanHorrik** [comment]
Are the pdb files also hosted privately? Note that adding a private token can be a bad idea and cause your source files to be exposed. This is obviously always the case when you need a token to get source code behind a login wall, but just want to make sure you understand the implications.

**Comment by Liryna** [comment]
Hi @GeertvanHorrik ,

Yes, the pdb are also hosted privately in a network shared folder.

**Comment by Liryna** [comment]
Oh, my bad, have not seen the `CustomUrlProvider`. This will do the work 👍
