### ISSUE TITLE
GitLink 3.1.0 not available on Chocolatey

### ISSUE THREAD

**Issue by schultetwin1** [GitTools/GitLink#208]
Version 3.0.0 does not support "-a". I'd love to be able to do choco install GitLink and get "-a".

**Comment by GeertvanHorrik** [comment]
I believe the prerelease versions are available? I think it was not allowed because it needed the license embedded or something like that.

**Comment by schultetwin1** [comment]
Ah, you are correct. The prerelease versions are there. Thanks!
