### ISSUE TITLE
Support {branch} in "File at commit template"

### ISSUE THREAD

**Issue by hzhr** [GitTools/GitLink#216]
### Steps to reproduce

1. Some git server use branch name in commit url
2. Add new Custom Platform, use {branch}  to set "File at commit template": https://xxx.server/xxx?branch={branch}&xxxx
3. GitLink, Open in XXX, or Copy XXX link

### Expected behaviour

{branch} is replaced by real branch name, eg: dev
The url is correct: https://xxx.server/xxx?branch=dev&xxxx

### Actual behaviour

{branch} is empty, the url is wrong: https://xxx.server/xxx?branch=&xxxx

**Comment by GeertvanHorrik** [comment]
Please use SourceLink instead, it's the recommended approach.
