### ISSUE TITLE
External provider support - visualstudio.com

### ISSUE THREAD

**Issue by AArnott** [GitTools/GitLink#53]
See http://visualstudio.com/

**Comment by AArnott** [comment]
It appears the way URLs work on visualstudio.com today, it will take more than one HTTP request per file to download its raw content. 

[Docs explaining the REST API for downloading files](https://www.visualstudio.com/integrate/api/git/items)

**Comment by GeertvanHorrik** [comment]
Looking for an open-source repository on visualstudio.com so we can test this.

**Comment by AArnott** [comment]
I could certainly push an open source git project to visualstudio.com for you to test against. But I wonder... visualstudio.com currently requires everyone to be authenticated. Can the source server enabled PDBs handle making authenticated HTTP calls (perhaps exposing the auth challenge to the user) or must it be anonymous HTTP?

**Comment by GeertvanHorrik** [comment]
We are considering that in #37. However, we need to figure out a safe way to store the credentials (on the remote computer, not in the pdb files).

**Comment by mattdkerr** [comment]
Was this ever merged? Git for Windows now uses Microsoft's contribution of Credential Manager, for the purposes of authentication for VSTS and others: https://github.com/Microsoft/Git-Credential-Manager-for-Windows

**Comment by GeertvanHorrik** [comment]
Sorry for the late reply. It was never merged.

**Comment by volak** [comment]
So this isn't in the latest 2.4 release?  

Kinda disappointed it seemed like some work has been done to support visualstudio.com - is there anything else that needs some work?

**Comment by GeertvanHorrik** [comment]
There are no open PR's, so it should be available. Could be that it's supported in the latest pre-release, not sure which version has this.

**Comment by GeertvanHorrik** [comment]
I think it's all coming back to me. This should be part of the 2.4.1 release. However, it's only available on chocolatey since NuGet.org though it had a virus (don't worry, it doesn't, it's a false positive because we use Costura). I already emailed them, but the NuGet team isn't very responsive.... Please try the one on chocolatey.

**Comment by GeertvanHorrik** [comment]
@volak / @mattdkerr please try the latest stable GitLink 3.0, it should work there as well now.

**Comment by GeertvanHorrik** [comment]
Closing this, if it's not solved, we'll re-open and fix this for 3.1.
