### ISSUE TITLE
Consider creating an msbuild task

### ISSUE THREAD

**Issue by GeertvanHorrik** [GitTools/GitLink#6]
Not sure if people want this. Will await comments on this issue report to see if it is worth the investment of implementing.

**Comment by krippz** [comment]
Hi don't know if this is of any interest but you might want to look at this project http://cakebuild.net
its a build system, you write c# tasks and it uses msbuild for the compilation all other tasks you might want you can write in c#. They have a system for addins, basically you write a wrapper for your tool in c# create a nuget of it and use it in your project.

**Comment by GeertvanHorrik** [comment]
I think @gep13 already wrote a cake task for GitLink.

**Comment by gep13** [comment]
@krippz @GeertvanHorrik I certainly did.  There is support for all the GitTools in Cake out of the box :smile:

**Comment by AArnott** [comment]
Isn't this closed by #81 ?

**Comment by GeertvanHorrik** [comment]
Good point, closing now.
