### ISSUE TITLE
Option to suppress errors

### ISSUE THREAD

**Issue by onovotny** [GitTools/GitLink#63]
Instead of having to enumerate projects to skip, I'd really like to just suppress error generation. The main scenario is appveyor where an error code is hard to ignore externally. I don't want to have to specify every project to skip, I'd rather just pass in a command line param to ignore all errors.

**Comment by GeertvanHorrik** [comment]
That means only the error output messages or also the exit code? We need to think about the impact (for example, what kind of errors could we ignore, what kind of errors can't we ignore).

**Comment by onovotny** [comment]
Error output messages are ok. It's the exit code that tools like AppVeyor parse and fail at. I'm not suggesting this be the default, but at least an option.

**Comment by GeertvanHorrik** [comment]
I can understand where you are coming from, but you are probably only interested in ignoring the "no pdb found" or "cannot parse project file" ones, right?

**Comment by onovotny** [comment]
yup

**Comment by onovotny** [comment]
Basically, I don't want to maintain an -ignore list as that's brittle and requires me to change the build tooling.

**Comment by GeertvanHorrik** [comment]
Let me think of a good switch name. If you have good ideas, let me know :-)

**Comment by onovotny** [comment]
how about a general /errorsAsWarnings = true and then the errors would be logged as warnings and the exit code is 0

**Comment by GeertvanHorrik** [comment]
Sounds good. I will put it on the list but need to finish a few other things first.

**Comment by GeertvanHorrik** [comment]
@onovotny latest prerelease (Build - 2.2.0-unstable.27) contains this feature. Please let me know if it works for you.

**Comment by onovotny** [comment]
Yes, that worked great! Let me get rid of this nasty PS hack in AppVeyor:

`- ps: '.\packages\gitlink\lib\net45\GitLink.exe . -f MetroLog.sln -u https://github.com/onovotny/metrolog -s $env:APPVEYOR_REPO_COMMIT;if($lastexitcode -ne 0){$lastexitcode = 0}'`

**Comment by GeertvanHorrik** [comment]
Great, thanks for letting me know! And glad that you can use it in a much easier way. If you have more ideas, let me know. I just need find to implement it, but now it's part of GitTools org, I might get some help ;-)
