### ISSUE TITLE
BitBucket repo's may have a period (.) in the name

### ISSUE THREAD

**Issue by neutmute** [GitTools/GitLink#70]
Given a URL to Bitbucket like:

https://bitbucket.org/mycorp/mycorp.framework/raw/7c5ace02a8a10c718ef54b17870e97c638c95a29

The regex in the provider incorrectly constructs the srcsrv url ike:

https://bitbucket.org/mycorp/mycorp/raw/7c5ace02a8a10c718ef54b17870e97c638c95a29

Dropping the `.framework` segment. I'll submit a PR to fix this

**Comment by GeertvanHorrik** [comment]
Thanks, much appreciated.
