### ISSUE TITLE
Specify which projects should be indexed

### ISSUE THREAD

**Issue by ivan-danilov** [GitTools/GitLink#75]
Instead of ignoring projects it would be nice if one could opt-in rather than opt-out. Often there's only one or two projects that are packaged, and many test ones that not need to be indexed because they never go outside of where they were built. Now it takes enumerating all of them in the `-ignore` option which is tedious.

**Comment by GeertvanHorrik** [comment]
I understand where you are coming from. Somehow I have a major deja vu feeling from this issue, but I can't remember why.

Shouldn't be too hard, interested in doing a PR?

**Comment by ivan-danilov** [comment]
Started to look where to implement tests and found one argument named `include` added in 35ee9d05fb2d5426a9ed9674b847d2484a080003. Probably that's why you have deja vu :)
As I've already decided to put some time here - I've added handling regex patterns both to includes and ignores, wrote dozen unit tests for them and updated readme, so that no one else will ask for the feature that is already there.

By the way, should I expect new release with these changes soon? I'd like to use it through Chocolatey actually. Thanks.

**Comment by GeertvanHorrik** [comment]
Awesome, thanks!

**Comment by GeertvanHorrik** [comment]
Just reviewed the code. A few minor changes, then I can accept. I will immediately release a prerelease on both NuGet and Chocolately.

**Comment by ivan-danilov** [comment]
Updated PR. Thanks)

**Comment by GeertvanHorrik** [comment]
Awesome, thanks! Build - 2.3.0-unstable.19 being released right now.

**Comment by adamralph** [comment]
How far away is 2.3.0 from a stable release? I'd love to start using `-include`.

**Comment by GeertvanHorrik** [comment]
Good one, I will bump it right now.

**Comment by GeertvanHorrik** [comment]
Done.

**Comment by adamralph** [comment]
Fantastic. Thanks!

You'll shortly have some new additions to https://github.com/GitTools/GitLink#projects-using-gitlink :smile:
