### ISSUE TITLE
Question: Updating dependent PDBs in bin/debug? 

### ISSUE THREAD

**Issue by raghur** [GitTools/GitLink#79]
So, this must be something simple(possibly). I'm building nuget packages from `bin/{Debug/Release}`.
Let's say I have A.csproj and B.csproj, with A referring to B. I'm packing the nuget out of A's bin/Debug folder. After my compile step,  if I run `GitLink` at the top level, then it updates the pdb files in A's bin/Debug and B's bin/Debug... the trouble is that the b.pdb has already been copied over to A's bin/debug folder and that copy's untouched.
Now I could potentially just recursively copy all .pdbs from the resp project folders, but that doesn't work without being able to walk each project's dependency tree. 
What would be great is if there's a way to not only update the project, but dependent pdbs as well found in bin/Debug.

Am I missing an obvious way of doing this that doesn't involve trying to redo what's already done in the Compilation step (copying over dependent dlls to the project's output folder)?

**Comment by GeertvanHorrik** [comment]
This might indeed be an issue. One solution is to cherry pick the right assemblies when creating the nuget package.

The question is: how do we know the dependencies? This requires us to read the project dependencies, check where their output files are, etc. I am open to this, but has very low prio to be honest. Interested in doing a PR?

**Comment by raghur** [comment]
PR: at some point in the future, yes. ATM, neck deep in things so don't have time to spare. I wonder though if it's possible that the MSBuild plugin takes care of this? ie. do the PDB update right after the project is built so that when outputs are copied over, it's the modified pdb that goes around?

Do you happen to know if that's how it works?

**Comment by GeertvanHorrik** [comment]
If I remember correctly, @distantcam was working on a PR with task support, but not sure if he is still on that path.

**Comment by GeertvanHorrik** [comment]
Task support is now fully implemented in 3.0
