### ISSUE TITLE
Add support for xproj+project.json

### ISSUE THREAD

**Issue by xoofx** [GitTools/GitLink#83]
Hi there,
Currently GitLink only supports regular msbuild projects (e.g csproj), and not xproj projects (dnx projects and upcoming dotnet/cli projects). I'm currently migrating all my projects to this model but cannot use GitLink with them.
Could you consider adding support for this kind of projects?
Thanks!

**Comment by GeertvanHorrik** [comment]
We are definitely open for this

**Comment by hikalkan** [comment]
Any update on that?

**Comment by GeertvanHorrik** [comment]
We haven't seen a PR yet. But on the other hand, glad we skipped the project.json ride now it's being replaced by csproj again.

**Comment by hikalkan** [comment]
Yes, it will be changed again. But for a few months (or more), there will be xproj files. Also, then csproj file will be different than current format. It would be good if GitLink supports both formats.

**Comment by hikalkan** [comment]
If this will not take much time, I definetely would like this. Because all new projects with .NET Core / ASP.NET Core support have xproj format now and I believe it will not be changed in a very short time. So, it has worth to support it.
Actually I did try to make it but and made it running. But there were some problems on debugging (was skipping some lines) since I don't know code well.
Thanks.

**Comment by GeertvanHorrik** [comment]
@hikalkan if you can create a pr with what you have so far, I am happy to help out and finish the feature together.

**Comment by hikalkan** [comment]
OK, It was a few weeks ago, I will check it again.

**Comment by niemyjski** [comment]
+1

**Comment by ejsmith** [comment]
Don't think it makes sense to do any work on this until they finalizing the new tooling.

**Comment by GeertvanHorrik** [comment]
Agree. It's a lot of work to implement this, from what I understood the project.json is going away again and being replaced by xproj.

**Comment by ghuntley** [comment]
3 cute kittens will be awarded to the victor (whomever raises and merges the PR)

![](https://cloud.githubusercontent.com/assets/127353/18228951/046a1778-72a7-11e6-8ceb-49bfca647d75.jpg)

**Comment by niemyjski** [comment]
@ghuntley does that include shots and free shipping?

**Comment by wocar** [comment]
Any updates on this :D

**Comment by GeertvanHorrik** [comment]
We are working on a version of GitLink that is solution / project unaware and only needs pdb files to work with. This would make this need redundant. It's WIP though.

**Comment by wocar** [comment]
Any updates on this hehe?? Should we put a bounty on the PR $ 😝😁 I'm down for it

**Comment by ejsmith** [comment]
Why would anyone work on this now? Project.json is about to be gone. Plus they said they are working on changes that will make it just work off the pdbs and not need the project

**Comment by ghuntley** [comment]
My vote is wait until 2017 is out/stable.

**Comment by niemyjski** [comment]
@ghuntley It should be good to work with the latest rc drop :)

**Comment by DanielBryars** [comment]
Do you have the version where you can specify the pdb file directly in a branch? I'd like to play with it?

**Comment by GeertvanHorrik** [comment]
@DanielBryars Yep, the current develop branch is that one. It's already available as pre-release on NuGet & Chocolatey as well.

**Comment by GeertvanHorrik** [comment]
GitLink 3.0 has just been released. I think this ticket can now be closed. If not, please feel free to comment / re-open.
