### ISSUE TITLE
srctool.exe -x not downloading source files

### ISSUE THREAD

**Issue by DavidKDeutsch** [GitTools/GitLink#84]
I have a pdb indexed by gitlink, but for some reason neither Visual Studio nor srctool.exe (with the -x option) attempts to download them. srctool correctly reports what the URLs are, so it knows where to get them, but just doesn't make a request to the web server. Any idea what might be going on? Is there a sample indexed pdb I can download that does work with Visual Studio, so I can see if this is just a problem with my local machine?

**Comment by GeertvanHorrik** [comment]
Do you have a symbols location set up in Visual Studio? It must have a location to store the symbols.

**Comment by DavidKDeutsch** [comment]
Yup. The problem turned out to be due to the fact that before attempting a download, VS uses the URL to create the directories/file in the symbol cache, and the URL I was hitting had query parameters in it, and '?' and '&' are not valid characters for a file name. Solved it by my having my IT guys set up the server to accept a URL in a different format and performing a redirect. Can't believe MS hasn't fixed this bug.
