### ISSUE TITLE
Latest 2.2.20 release doesn't contain executable

### ISSUE THREAD

**Issue by kjeremy** [GitTools/GitLink#85]
The 2.2.0 release only contains the zipped source on the releases tab in github.  The older releases contain a downloadable executable.

**Comment by GeertvanHorrik** [comment]
Correct. We deploy the executable to both nuget and chocolatey.

**Comment by sandersaares** [comment]
When can we expect a fix to this issue? Downloading a zip is way easier than having to install something from some package store.

**Comment by GeertvanHorrik** [comment]
I will add the executable now.

**Comment by GeertvanHorrik** [comment]
Done.
