### ISSUE TITLE
GitLink.exe should in 'tools' folder instead of 'lib'

### ISSUE THREAD

**Issue by nobitagamer** [GitTools/GitLink#87]
In the latest version published on nuget.org the .exe file is inside 'lib' folder but the package i downloaded on 06/21/2016 it's in corrected 'tools' folder

**Comment by GeertvanHorrik** [comment]
From what I remember at the time I wrote it, my logic was that via NuGet, you want to use as library (thus lib), from chocolatey it installs as a tool.

**Comment by dazinator** [comment]
I use NuGet for tools packages quite a bit, I find it convenient for them to be in my solution directory and restored on package restore. Imho it would definitely make more sense to have a tools package, as consuming GitLink.exe is probably much more likely the intention, than referencing the library. No harm in having an additional nuget package for the library though

**Comment by tpluscode** [comment]
@dazinator It's sidestepping the issue, but if and only if you would consider using [Paket](https://github.com/fsprojects/Paket) instead of the default package manager, you'll be able to add Nugets to your solution without actually referring them in any project - true tools-only usage.

**Comment by pkiers** [comment]
Hey,
Did you hear the latest news? You should definetely read more info here <http://enjoy.suryaplastindo.com/e2paeg>

Yours sincerely, p.kiers@home.nl

**Comment by GeertvanHorrik** [comment]
It's now inside the build folder since GitLink directly integrations with msbuild.

**Comment by dazinator** [comment]
@GeertvanHorrik  that's cool - does the build task run under dotnet core - can is there a sample with it being used with the new vs2017 csproj format somewhere? Is it as simple as just adding a `PackageRefernece` or do you need to add a cli tools package reference?

**Comment by GeertvanHorrik** [comment]
From the readme:

-----

The simplest way to use GitLink is to install its NuGet package into your project.

```
Install-Package GitLink
```

Once installed, it automatically integrates with MSBuild to add source download instructions to your PDB.

-----

I haven't tested against dotnet core just yet, but it depends whether you are using portable pdb's or not. For portable pdb support, this will be (or already is) in SourceLink. We're trying to combine efforts with the SourceLink team to come up with a single solution that works for all.

**Comment by dazinator** [comment]
@GeertvanHorrik Cheers. If your msbuild task is built on the full desktop version of the msbuild assemblies (i.e if these references are the desktop version of msbuild: https://github.com/GitTools/GitLink/blob/develop/src/GitLinkTask/GitLinkTask.csproj#L53) then `dotnet build` won't work as the dotnet cli tooling (an the version of msbuild used) will complain that it can load the task.

I believe you have to build your task against the netstandard compatible msbuild assemblies - I.e: https://www.nuget.org/packages/Microsoft.Build.Framework/15.3.0-preview-000388-01
