### ISSUE TITLE
Skipping projects not selected for build

### ISSUE THREAD

**Issue by tpluscode** [GitTools/GitLink#89]
With the `-f X.sln` switch GitLink is smart enough to only process projects from the solution, which is great.

I've found however that it also tries to process projects not selected for building given the **Configuration**/**Platform** combination. 

Maybe they should be skipped by GitLink as well?

**Comment by GeertvanHorrik** [comment]
I think you are right. Interested in doing a PR?

**Comment by tpluscode** [comment]
Sure. I see that the necessary information is included in the `Microsoft.Build.Construction.*` types but a lot of it internal. Would you mind me using [ImpromptuInterface](https://github.com/ekonbenefits/impromptu-interface)'s [`ActLike` feature](https://github.com/ekonbenefits/impromptu-interface/wiki/UsageBasic) instead of reflection and adding it to Costura?
