### ISSUE TITLE
Sources found but not downloaded

### ISSUE THREAD

**Issue by StephenCleary** [GitTools/GitLink#94]
[This GitHub project](https://github.com/exceptionless/Foundatio.Repositories) is attempting to use GitLink ([run in AppVeyor](https://ci.appveyor.com/project/Exceptionless/foundatio-repositories/build/2.0.194#L262)) for [this branch](https://github.com/exceptionless/Foundatio.Repositories/tree/feature/config-refactor), which does create a source-indexed pdb in [the NuGet package](https://www.nuget.org/packages/Foundatio.Repositories.Elasticsearch/2.0.194-pre).

However, Visual Studio 2015 (running on Windows 10) does not download the source files. Neither does srctool; it only displays them, but will not download them. There are no error messages or warnings.

Result of `pdbstr -r -p:.\Foundatio.Repositories.Elasticsearch.pdb -s:srcsrv -i:pdbstr.txt` [pdbstr.txt](https://github.com/GitTools/GitLink/files/450041/pdbstr.txt)

Result of `srctool .\Foundatio.Repositories.Elasticsearch.pdb > srctool.txt` [srctool.txt](https://github.com/GitTools/GitLink/files/450048/srctool.txt)

Result of `srctool -n -x .\Foundatio.Repositories.Elasticsearch.pdb -d:. > srctool.extract.txt` [srctool.extract.txt](https://github.com/GitTools/GitLink/files/450068/srctool.extract.txt) (note that no source files were actually written to disk, in spite of the "51 source files were extracted" message).

According to Fiddler, neither `srctool` (nor anything else) are requesting the URLs. According to Process Monitor, `srctool` is opening its output directory once per URL, but that is all. No actual files are created.

**Comment by GeertvanHorrik** [comment]
1. Have you included the PDB files inside the nuget package?
2. Have you enabled source stepping inside visual studio?
3. Have you disabled "my source only"?

**Comment by StephenCleary** [comment]
Yes; yes; and yes.

Upon further investigation, it looks like stepping into *synchronous* methods works fine, but stepping into *asynchronous* methods does not work.

I just tried this test code:

    var c = new Foundatio.Repositories.Elasticsearch.Configuration.ElasticConfiguration(null, null, null, null);
    await c.ReindexAsync();

(in the context of an xUnit unit test run via the Visual Studio runner)

It's able to step into the ElasticConfiguration constructor just fine, but won't step into ReindexAsync. If I set a breakpoint in ReindexAsync after stepping into the constructor, then the breakpoint will be hit.

This is looking more an more like a bug in Visual Studio itself.

**Comment by GeertvanHorrik** [comment]
Yes, this is "normal". The reason is that the method immediately returns a task (the debugger is not aware of awaits or doesn't support it).

**Comment by StephenCleary** [comment]
It still won't step into it, which is definitely a bug. Asynchronous methods begin executing synchronously, and even if you call it as `var task = c.ReindexAsync();`, it won't step into it.

Probably related to [this](http://inedo.com/support/questions/4063).

Closing this, since it is definitely a Visual Studio bug. Reported [here](https://connect.microsoft.com/VisualStudio/feedback/details/3100945/unable-to-download-source-files-over-https).

**Comment by StephenCleary** [comment]
If you're interested, there's a repro [here](https://github.com/StephenCleary/GitLinkTestConsole), using [this GitLinked library](https://github.com/StephenCleary/GitLinkTestLib). I'll keep you updated with Microsoft's response.

**Comment by GeertvanHorrik** [comment]
Very nice, thanks for keeping us up-to-date.
